name: Commit Checks

on:
  push:
    branches:
      - master # veya kullanmakta olduğunuz ana branch adı
    paths:
      - '**/*.ts'
      - '.github/workflows/commit-check.yml'
      - '.github/workflows/commit-template.txt'
      - '.husky/commit-msg' # commit-msg dosyanızın yolu

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Projenizin gereksinimlerine göre ayarlayın

      - name: Install dependencies
        run: yarn install

      - name: Run commit-msg hook
        run: |
          # Ensure commit-msg script is executable
          chmod +x .husky/commit-msg
          # Run the commit-msg script with the actual commit-template file
          .husky/commit-msg .github/workflows/commit-template.txt || exit 1

      - name: Check commit tense
        run: |
          npx ts-node check-tense-commit.ts .github/workflows/commit-template.txt || exit 1
