name: Commit Lint

on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:
    branches:
      - master
      - main
      - dev

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Get last commit message
        run: |
          echo "Last commit message: $(git log -1 --pretty=format:%s)"

      - name: Run commitlint
        run: |
          echo "Running commitlint from ${GITHUB_EVENT_BEFORE} to ${GITHUB_SHA}"
          yarn commitlint --from=${GITHUB_EVENT_BEFORE} --to=${GITHUB_SHA}
        continue-on-error: false

      - name: Report errors
        if: failure()
        run: |
          echo "Commitlint errors found" >> commitlint-errors.log
           cat commitlint-errors.log
