name: Commit Lint

on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:
    branches:
      - master
      - main
      - dev

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint commits
        run: yarn commitlint --from=${{ github.event.before }} --to=${{ github.sha }}

      - name: Upload commitlint report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: commitlint-report
          path: ./commitlint-report.txt
          retention-days: 7

      - name: Display failure message
        if: failure()
        run: echo "Commit linting failed. Please check the commitlint report for details."
