name: Commit Lint

on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:
    branches:
      - master
      - main
      - dev

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Get commit details
        id: commit_details
        run: |
          # Get all commit hashes
          COMMITS=$(git log --pretty=format:"%H" -n 2)

          # Count the number of commits
          COMMITS_COUNT=$(echo "$COMMITS" | wc -l)

          # Extract the current and previous SHA if we have at least 2 commits
          if [ "$COMMITS_COUNT" -ge 2 ]; then
            CURRENT_SHA=$(echo "$COMMITS" | head -n 1)
            PREVIOUS_SHA=$(echo "$COMMITS" | tail -n 1)
            LAST_COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
            echo "LAST_COMMIT_MESSAGE=${LAST_COMMIT_MESSAGE}" >> $GITHUB_ENV
            echo "CURRENT_SHA=${CURRENT_SHA}" >> $GITHUB_ENV
            echo "PREVIOUS_SHA=${PREVIOUS_SHA}" >> $GITHUB_ENV
          else
            echo "Not enough commits to determine a range. Skipping commitlint."
            echo "CURRENT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
            echo "PREVIOUS_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          fi

      - name: Run commitlint
        if: env.PREVIOUS_SHA != env.CURRENT_SHA
        run: |
          echo "Running commitlint from ${PREVIOUS_SHA} to ${CURRENT_SHA}"
          yarn commitlint --from=${PREVIOUS_SHA} --to=${CURRENT_SHA}
        continue-on-error: false

      - name: Send email on commitlint failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Commitlint failed in ${{ github.repository }}
          body: |
            Commitlint errors were detected in the latest commit(s) in the ${{ github.repository }} repository.
            Commit range: ${PREVIOUS_SHA} to ${CURRENT_SHA}.
            Last commit message: ${{ env.LAST_COMMIT_MESSAGE }}
          to: 'ceser446@gmail.com'
          from: ${{ secrets.MAIL_USERNAME }}
          secure: true
