name: Commit Lint

on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:
    branches:
      - master
      - main
      - dev

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Get commit details
        id: commit_details
        run: |
          echo "LAST_COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)" >> $GITHUB_ENV
          echo "GITHUB_EVENT_BEFORE=${GITHUB_EVENT_BEFORE}" >> $GITHUB_ENV
          echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "Debug: GITHUB_EVENT_BEFORE=${GITHUB_EVENT_BEFORE}" # Debugging line

      - name: Run commitlint
        run: |
          if [ -z "${GITHUB_EVENT_BEFORE}" ]; then
            echo "GITHUB_EVENT_BEFORE is empty. Skipping commitlint check."
            exit 0
          fi
          echo "Running commitlint from ${GITHUB_EVENT_BEFORE} to ${GITHUB_SHA}"
          yarn commitlint --from=${GITHUB_EVENT_BEFORE} --to=${GITHUB_SHA}
        continue-on-error: false

      - name: Send email on commitlint failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Commitlint failed in ${{ github.repository }}
          body: |
            Commitlint errors were detected in the latest commit(s) in the ${{ github.repository }} repository.
            Commit range: ${{ env.GITHUB_EVENT_BEFORE }} to ${{ env.GITHUB_SHA }}.
            Last commit message: ${{ env.LAST_COMMIT_MESSAGE }}
          to: 'ceser446@gmail.com'
          from: ${{ secrets.MAIL_USERNAME }}
          secure: true
