name: Commit Checks

on:
  push:
    branches:
      - master # veya kullanmakta olduğunuz ana branch adı
    paths:
      - '**/*.ts'
      - '.github/workflows/commit-check.yml'
      - '.github/workflows/commit-template.txt'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Projenizin gereksinimlerine göre ayarlayın

      - name: Install dependencies
        run: yarn install

      - name: Check commit message format
        run: |
          # Check the latest commit message format
          git log -1 --pretty=%B | npx --no-install commitlint || {
            echo "Commit message format is incorrect."
            exit 1
          }

      - name: Check commit tense
        run: |
          git log -1 --pretty=%B > .git/COMMIT_EDITMSG
          npx ts-node check-tense-commit.ts .git/COMMIT_EDITMSG || {
            exit 1
          }
