name: Commit Checks

on:
  push:
    branches:
      - master # veya kullanmakta olduğunuz ana branch adı
    paths:
      - '**/*.ts'
      - '.github/workflows/commit-check.yml'
      - '.github/workflows/commit-template.txt'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Projenizin gereksinimlerine göre ayarlayın

      - name: Install dependencies
        run: yarn install

      - name: Check commit message format
        run: |
          COMMIT_TEMPLATE_FILE=".github/workflows/commit-template.txt"
          if [ -f "$COMMIT_TEMPLATE_FILE" ]; then
            COMMIT_TEMPLATE=$(cat "$COMMIT_TEMPLATE_FILE")
          else
            echo "Commit template file not found."
            exit 1
          fi

          npx --no-install commitlint --edit $1 || {
            echo "$COMMIT_TEMPLATE"
            exit 1
          }

      - name: Check commit tense
        run: |
          npx ts-node check-tense-commit.ts "$1" || {
            exit 1
          }
