name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Sadece `main` dalına push yapıldığında çalıştırır

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build Storybook
        run: yarn build-storybook

      - name: Verify Storybook output directory
        run: ls -la

      - name: Create directories if not exist
        run: mkdir -p public/storybook public/docs

      - name: Move Storybook to public directory
        run: mv .out/* public/storybook

      - name: Build TypeDoc
        run: yarn typedoc

      - name: Move TypeDoc to public directory
        run: mv docs/* public/docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
