name: ESLint and Prettier

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run Prettier
        run: yarn prettier

      - name: Run ESLint
        run: yarn lint

      - name: Send email ESLint and Prettier
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: ESLint and Prettier failed in ${{ github.repository }}
          body: |
            ESLint and Prettier failed in ${{ github.repository }}.
            Check the logs for more information.
          to: 'ceser446@gmail.com'
          from: ${{ secrets.MAIL_USERNAME }}
          attachments: 'eslint.log, prettier.log'
