# github_pages kullanabilmek için reponun public olması gerekmektedir.
# Daha sonra reponun settings kısmından github pages kısmını aktif hale getirin.
# Orada master branch ve /docs klasörü seçili olmalıdır.
# DEPLOY_TOKEN adında bir secret oluşturun ve içine github tokeninizi ekleyin.
# Bu tokeni oluştururken repo erişimi vermelisiniz.
# Bu tokeni Github Settings -> Developer Settings -> Personal Access Tokens -> Generate new token kısmından oluşturabilirsiniz.
name: TypeDoc

on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:
    branches:
      - master
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run TypeDoc
        run: yarn typedoc

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
